enum CauseMort {
  Mise_bas,
  Pas_de_contraction_dilatation,
  Prolapsus,
  Mal_place,
  Noye,
  Trop_gros,
  Cesarienne,
  Brebis_malade_toxemie,
  Conformation,
  Malforme,
  chetif_maigre,
  Tetee,
  Incapacite_a_teter,
  Brebis_sans_lait,
  Non_accepte,
  Sanitaire,
  Mou,
  Baveur_colibacilose,
  Trembleur_hirsute_border,
  Ecthyma,
  Respiratoire,
  Arthrite_gros_nombril,
  Lithiase_urinaire,
  Nerveux_metabolique,
  Raide,
  Tetanos,
  Necrose_cortex_cerebral,
  Digestif,
  Diarrhee,
  Ballonne_enterotoxemie,
  Coccidiose,
  Autres,
  Ecrase,
  Maigre,
  Accident,
  Disparu,
  Autre,
  Inconnue}

extension CauseMortExtension on CauseMort {
  static const documentation = {
  CauseMort.Mise_bas:"Mise-bas",
  CauseMort.Pas_de_contraction_dilatation:"Pas de contraction/dilatation",
  CauseMort.Prolapsus: "Prolapsus",
  CauseMort.Mal_place: "Mal placé",
  CauseMort.Noye: "Noyé, pas respiré(dans poches)",
  CauseMort.Trop_gros: "Trop gros",
  CauseMort.Cesarienne: "Césarienne",
  CauseMort.Brebis_malade_toxemie: "Brebis malade / toxémie",
  CauseMort.Conformation: "Conformation de l’agneau",
  CauseMort.Malforme: "Malformé",
  CauseMort.chetif_maigre: "Très petit / chétif / maigre",
  CauseMort.Tetee: "Tétée",
  CauseMort.Incapacite_a_teter: "Incapacité à téter",
  CauseMort.Brebis_sans_lait: "Brebis sans lait",
  CauseMort.Non_accepte: "Non accepté",
  CauseMort.Sanitaire: "Sanitaire",
  CauseMort.Mou: "Mou",
  CauseMort.Baveur_colibacilose: "Baveur (colibacilose)",
  CauseMort.Trembleur_hirsute_border: "Trembleur hirsute (border)",
  CauseMort.Ecthyma: "Ecthyma",
  CauseMort.Respiratoire: "Respiratoire",
  CauseMort.Arthrite_gros_nombril: "Arthrite / gros nombril",
  CauseMort.Lithiase_urinaire: "Lithiase urinaire",
  CauseMort.Nerveux_metabolique: "Nerveux / métabolique",
  CauseMort.Raide: "Raide",
  CauseMort.Tetanos: "Tétanos",
  CauseMort.Necrose_cortex_cerebral: "Nécrose du cortex cérébral",
  CauseMort.Digestif: "Digestif",
  CauseMort.Diarrhee: "Diarrhée",
  CauseMort.Ballonne_enterotoxemie: "Ballonné ou entérotoxémie",
  CauseMort.Coccidiose: "Coccidiose",
  CauseMort.Autres: "Autres",
  CauseMort.Ecrase: "Ecrasé",
  CauseMort.Maigre: "Maigre",
  CauseMort.Accident: "Accident",
  CauseMort.Disparu: "Disparu",
  CauseMort.Autre: "Autre",
  CauseMort.Inconnue: "Inconnue"
  };

  static const codeIdele = {
    CauseMort.Mise_bas:"010000",
    CauseMort.Pas_de_contraction_dilatation: "010200",
    CauseMort.Prolapsus:"010300",
    CauseMort.Mal_place:"010400",
    CauseMort.Noye:"010500",
    CauseMort.Trop_gros:"010600",
    CauseMort.Cesarienne:"010700",
    CauseMort.Brebis_malade_toxemie:"012500",
    CauseMort.Conformation:"020000",
    CauseMort.Malforme:"020100",
    CauseMort.chetif_maigre:"020800",
    CauseMort.Tetee:"030000",
    CauseMort.Incapacite_a_teter:"031300",
    CauseMort.Brebis_sans_lait:"032400",
    CauseMort.Non_accepte:"032600",
    CauseMort.Sanitaire:"040000",
    CauseMort.Mou:"040900",
    CauseMort.Baveur_colibacilose:"041000",
    CauseMort.Trembleur_hirsute_border:"041100",
    CauseMort.Ecthyma:"041800",
    CauseMort.Respiratoire:"041900",
    CauseMort.Arthrite_gros_nombril:"042000",
    CauseMort.Lithiase_urinaire:"042300",
    CauseMort.Nerveux_metabolique:"045000",
    CauseMort.Raide:"045016",
    CauseMort.Tetanos:"045017",
    CauseMort.Necrose_cortex_cerebral:"045021",
    CauseMort.Digestif:"045100",
    CauseMort.Diarrhee:"045112",
    CauseMort.Ballonne_enterotoxemie:"045125",
    CauseMort.Autres:"050000",
    CauseMort.Coccidiose:"045127",
    CauseMort.Ecrase:"051400",
    CauseMort.Maigre:"052200",
    CauseMort.Accident:"052800",
    CauseMort.Disparu:"052900",
    CauseMort.Autre:"053000",
    CauseMort.Inconnue:"060000",
  };

  String get name => documentation[this];
  String get code => codeIdele[this];

  static CauseMort getValue(String value) {
    return CauseMort.values.firstWhere((e) => e.toString() == 'CauseMort.' + value);
  }
}